version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: bookora-postgres
    environment:
      POSTGRES_DB: bookora
      POSTGRES_USER: bookora
      POSTGRES_PASSWORD: bookora
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookora -d bookora"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  bookora-network:
    driver: bridge
