version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: bookora-postgres
    environment:
      POSTGRES_DB: bookora
      POSTGRES_USER: bookora
      POSTGRES_PASSWORD: bookora
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - bookora-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookora -d bookora"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:latest
    container_name: bookora-mailpit
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    networks:
      - bookora-network
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8025/api/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres-data:
    driver: local

networks:
  bookora-network:
    driver: bridge
